# Generated by Django 5.2.16 on 2026-07-28 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('external_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('voting_date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-voting_date', '-external_id'],
            },
        ),
        migrations.CreateModel(
            name='DeputyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputy_id', models.PositiveBigIntegerField(db_index=True)),
                ('deputy_name', models.CharField(blank=True, max_length=255)),
                ('party', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('vote', models.CharField(max_length=50)),
                ('vote_registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_votes', to='politicians.voting')),
            ],
            options={
                'ordering': ['-voting__voting_date', '-vote_registered_at'],
                'constraints': [models.UniqueConstraint(fields=('voting', 'deputy_id'), name='unique_deputy_vote_per_voting')],
            },
        ),
    ]
