# Generated by Django 5.2.16 on 2026-07-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('ibge_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('state', models.CharField(default='SP', max_length=2)),
                ('immediate_region', models.CharField(blank=True, max_length=150)),
                ('intermediate_region', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'ordering': ['name'],
            },
        ),
    ]
