# Generated by Django 5.2.16 on 2026-07-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalOfficeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MAYOR', 'Mayor'), ('VICE_MAYOR', 'Vice-mayor')], max_length=20)),
                ('tse_candidate_id', models.PositiveBigIntegerField(db_index=True)),
                ('tse_municipality_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('ballot_name', models.CharField(blank=True, max_length=255)),
                ('social_name', models.CharField(blank=True, max_length=255)),
                ('party', models.CharField(blank=True, max_length=30)),
                ('party_name', models.CharField(blank=True, max_length=150)),
                ('coalition_name', models.CharField(blank=True, max_length=255)),
                ('coalition_composition', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_state', models.CharField(blank=True, max_length=2)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=60)),
                ('race', models.CharField(blank=True, max_length=40)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('election_date', models.DateField()),
                ('election_type', models.CharField(max_length=100)),
                ('election_round', models.PositiveSmallIntegerField(default=1)),
                ('electoral_status', models.CharField(max_length=60)),
                ('source_url', models.URLField(max_length=500)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officeholders', to='politicians.municipality')),
            ],
            options={
                'ordering': ['role', 'name'],
                'constraints': [models.UniqueConstraint(fields=('municipality', 'role'), name='unique_municipal_officeholder_role')],
            },
        ),
    ]
