# Generated by Django 5.2.16 on 2026-08-03 13:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0003_municipalofficeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalofficeholder',
            name='asset_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='campaign_expense_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='campaign_expense_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='campaign_revenue_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='campaign_revenue_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='declared_assets_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='declared_assets_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='expense_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='finance_data_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipalofficeholder',
            name='revenue_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
