# Generated by Django 5.2.16 on 2026-08-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0004_municipalofficeholder_asset_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('tse_candidate_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('tse_municipality_code', models.CharField(db_index=True, max_length=10)),
                ('election_year', models.PositiveSmallIntegerField(db_index=True)),
                ('election_date', models.DateField(db_index=True)),
                ('election_type', models.CharField(max_length=100)),
                ('election_description', models.CharField(max_length=180)),
                ('election_round', models.PositiveSmallIntegerField(default=1)),
                ('office', models.CharField(db_index=True, max_length=80)),
                ('candidate_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ballot_name', models.CharField(db_index=True, max_length=255)),
                ('social_name', models.CharField(blank=True, max_length=255)),
                ('party', models.CharField(db_index=True, max_length=30)),
                ('party_name', models.CharField(blank=True, max_length=150)),
                ('federation_name', models.CharField(blank=True, max_length=255)),
                ('federation_composition', models.TextField(blank=True)),
                ('coalition_name', models.CharField(blank=True, max_length=255)),
                ('coalition_composition', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_state', models.CharField(blank=True, max_length=2)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=60)),
                ('race', models.CharField(blank=True, max_length=40)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('candidacy_status', models.CharField(db_index=True, max_length=80)),
                ('result_status', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_url', models.URLField(max_length=500)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='politicians.municipality')),
            ],
            options={
                'ordering': ['-election_date', 'office', 'ballot_name'],
            },
        ),
    ]
