# Generated by Django 5.2.16 on 2026-08-03 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0005_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='asset_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assets_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='declared_assets_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='declared_assets_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
    ]
