# Generated by Django 5.2.16 on 2026-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0007_candidate_campaign_revenue_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election_scope',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
