# Generated by Django 5.2.16 on 2026-08-03 14:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0008_candidate_election_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='campaign_expense_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_expense_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expense_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expenses_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
