# Generated by Django 5.2.16 on 2026-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0009_candidate_campaign_expense_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='has_government_proposal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='proposal_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
